general:
  buildTool: 'npm'
  productiveBranch: 'main'
  pipelineOptimization: false
  gitHttpsCredentialsId: 'hyperspace-github-tools-sap-i545698'
  vaultAppRoleTokenCredentialsId: 'vault-approle-role-id-3103-26250'
  vaultAppRoleSecretTokenCredentialsId: 'vault-approle-secret-id-accessor-3103-26250'
  vaultPath: 'piper/PIPELINE-GROUP-3103'
  vaultBasePath: 'piper/PIPELINE-GROUP-3103'
  vaultPipelineName: 'PIPELINE-26250'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/hyperspace/pipelines'
  nativeBuild: true
  nativeVoting: true
  verbose: true
steps:
  checkmarxExecuteScan:
    avoidDuplicateProjectScans: false
    projectName: cdc-tools-chrome-extension
    checkmarxCredentialsId: f262c01d-ba51-4591-afcb-8c5c77e9d4c2
    filterPattern: '!**/node_modules/**,!**/coverage/**,!**/whitesource/**,!**/build/**,**/*.html, **/*.xml, **/*.js, **/*.jsx'
    failBuildOnNewResults: false
    failBuildOnNewSeverity: 'MEDIUM'
    fullScanCycle: 5
    generatePdfReport: true
    includeOpenSourceFolders: ''
    incremental: false
    osaArchiveIncludePatterns: '*.zip, *.war, *.ear, *.tgz'
    osaInstallBeforeScan: false
    preset: 'SAP_Corp_JavaScript_Client' # https://github.wdf.sap.corp/pages/Security-Testing/doc/checkmarx/Presets/
    sastEnabled: true
    serverUrl: 'https://cx.wdf.sap.corp:443'
    sourceEncoding: '1'
    teamName: '/CxServer/SP/SAP/PI/SMEDevelopmentSupport/SMECoreB1Program' # 502
    vulnerabilityThresholdResult: 'FAILURE'
    waitForResultsEnabled: true
  whitesourceExecuteScan:
    whitesourceProductName: 'SHC - CXA CDC TOOLKIT 1.0'
    whitesourceProductToken: '611e7a74814a450b8bf1d2e34e680afc130fb28774a3464f81aea4f115450126'
    whitesourceUserTokenCredentialsId: 'whitesource'
  sonarExecuteScan:
    serverUrl: 'https://sonar.tools.sap'
    sonarTokenCredentialsId: 'hyperspace-sonar-i545698'
    sonarVaultSecretName: 'GROUP-SECRETS/sonar-cdc-sonar-token'
    waitForQualityGate: true
