general:
  buildTool: 'npm'
  productiveBranch: 'main'
  pipelineOptimization: false
  gitHttpsCredentialsId: 'hyperspace-github-tools-sap-i545698'
  vaultAppRoleTokenCredentialsId: 'vault-approle-role-id-3103-45640'
  vaultAppRoleSecretTokenCredentialsId: 'vault-approle-secret-id-accessor-3103-45640'
  vaultPath: 'piper/PIPELINE-GROUP-3103'
  vaultBasePath: 'piper/PIPELINE-GROUP-3103'
  vaultPipelineName: 'PIPELINE-45640'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/hyperspace/pipelines'
  nativeBuild: true
  nativeVoting: true
stages:
  Build:
    hadolintExecute: false
steps:
  artifactPrepareVersion:
    gitHttpsCredentialVaultSecretName: 'GROUP-SECRETS/github-cdc-github'
    versioningType: 'cloud_noTag'
  executeBuild:
    buildType: stage
  sapCallStagingService:
    url: 'https://staging.repositories.cloud.sap/stage/api'
    profile: 'group-3103-default'
  checkmarxOneExecuteScan:
    projectName: 'sap-customer-data-cloud-toolkit-2025'
    applicationName: 'OS_CX_AUTOMATION'
    preset: 'SAP_Corp_JavaScript_Client' # you can find the preset per language here - https://github.wdf.sap.corp/pages/Security-Testing/doc/cxone/Presets/
    filterPattern: '!**/node_modules/**,!**/coverage/**,!**/whitesource/**,!**/build/**,**/*.html, **/*.xml, **/*.js, **/*.jsx'
  sapCheckPPMSCompliance:
    ppmsCredentialsId: 'hyperspace-ppmsfoss-cxbt_api'
    ppmsID: '73555000106100155341'
    uploadChangeRequest: true
    whitesourceProductToken: '724f6571b0ec47b89cf24c1b4d5319d079d83c3da2d04aacb7a4efa0eb98a1b3'
  whitesourceExecuteScan:
    buildTool: 'npm'
    userTokenCredentialsId: cdc-tools-chrome-extension-whitesource
    productName: cdc-tools-chrome-extension
    projectName: sap-customer-data-cloud-toolkit
    serviceUrl: 'https://sap.whitesourcesoftware.com/api/v1.4'
    agentUrl: 'https://sap.whitesourcesoftware.com/agent'
    verbose: true
    agentDownloadUrl: 'https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar'
    #includes: ['*/src/*, **/*.html, **/*.xml, **/*.js, **/*.jsx, **/*.json']
    #excludes: ['**/node_modules/**', '**/coverage/**', '**/build/**']
    productToken: '724f6571b0ec47b89cf24c1b4d5319d079d83c3da2d04aacb7a4efa0eb98a1b3'
    orgToken: '6971b2eec2d3420bad0caf173ec629f6a3c7d3ba63f3445ab99ffdbf1acfb1d0'
    projectToken: '903dc851f55b43778b3180f0a484800a5a57e7245e9b44bb9096338692519b2d'
  sonarExecuteScan:
    serverUrl: 'https://sonar.tools.sap'
    sonarVaultSecretName: 'GROUP-SECRETS/sonar-cdc-sonar-token'
    waitForQualityGate: true
  sapCumulusUpload:
    pipelineId: '99a5c6dc-e368-4f20-b5c0-58f0e4a3e571'
  npmExecuteScripts:
    dockerImage: 'cypress/browsers:node-20.13.0-chrome-124.0.6367.155-1-ff-125.0.3-edge-124.0.2478.80-1'
    runScripts:
      - test
      - cypress:ci