general:
  buildTool: 'npm'
  productiveBranch: 'main'
  vaultPath: 'piper/sap-project-sap-customer-data-cloud-toolkit'
  vaultBasePath: 'piper/sap-project-sap-customer-data-cloud-toolkit'
  vaultPipelineName: 'sap-customer-data-cloud-toolkit'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/hyperspace/pipelines'
  nativeBuild: true
stages:
  Release:
    sapDownloadArtifact: false
  Post:
    vaultRotateSecretId: false
steps:
  sapCumulusUpload:
    pipelineId: '81afc9cc-82f5-4e86-ac69-74b2be490191'
  npmExecuteScripts:
    publish: true
    publishTag: 'next'
    runScripts:
      - 'test'
      - 'cypress:ci'
  checkmarxOneExecuteScan:
    projectId: 'e60bd89e-aca4-46f5-aeb0-cebffe755279'
    preset: 'SAP_Corp_JavaScript'
  sonarExecuteScan:
    serverUrl: 'https://sonar.tools.sap'
