general:
  buildTool: 'npm'
steps:
  checkmarxExecuteScan:
    avoidDuplicateProjectScans: false
    projectName: cdc-tools-chrome-extension
    checkmarxCredentialsId: f262c01d-ba51-4591-afcb-8c5c77e9d4c2
    filterPattern: '!**/node_modules/**,!**/coverage/**,!**/build/**,**/*.html, **/*.xml, **/*.js, **/*.jsx'
    failBuildOnNewResults: false
    failBuildOnNewSeverity: 'MEDIUM'
    fullScanCycle: 5
    generatePdfReport: true
    includeOpenSourceFolders: ''
    incremental: false
    osaArchiveIncludePatterns: '*.zip, *.war, *.ear, *.tgz'
    osaInstallBeforeScan: false
    preset: 'SAP_Corp_JavaScript_Client' # https://github.wdf.sap.corp/pages/Security-Testing/doc/checkmarx/Presets/
    sastEnabled: true
    serverUrl: 'https://cx.wdf.sap.corp:443'
    sourceEncoding: '1'
    teamName: '/CxServer/SP/SAP/PI/SMEDevelopmentSupport/SMECoreB1Program' # 502
    vulnerabilityThresholdResult: 'FAILURE'
    waitForResultsEnabled: true
  whitesourceExecuteScan:
    userTokenCredentialsId: 003682439bbc43a59cfa74df5fcc0843769c1df9d9e44f6591f9cc56aada9b2a
    productName: cdc-tools-chrome-extension
    projectName: cdc-tools-chrome-extension
    verbose: true
