general:
  buildTool: 'npm'
  verbose: true
steps:
  checkmarxExecuteScan:
    avoidDuplicateProjectScans: false
    projectName: cdc-tools-chrome-extension
    checkmarxCredentialsId: f262c01d-ba51-4591-afcb-8c5c77e9d4c2
    filterPattern: '!**/node_modules/**,!**/coverage/**,!**/whitesource/**,!**/build/**,**/*.html, **/*.xml, **/*.js, **/*.jsx'
    failBuildOnNewResults: false
    failBuildOnNewSeverity: 'MEDIUM'
    fullScanCycle: 5
    generatePdfReport: true
    includeOpenSourceFolders: ''
    incremental: false
    osaArchiveIncludePatterns: '*.zip, *.war, *.ear, *.tgz'
    osaInstallBeforeScan: false
    preset: 'SAP_Corp_JavaScript_Client' # https://github.wdf.sap.corp/pages/Security-Testing/doc/checkmarx/Presets/
    sastEnabled: true
    serverUrl: 'https://cx.wdf.sap.corp:443'
    sourceEncoding: '1'
    teamName: '/CxServer/SP/SAP/PI/SMEDevelopmentSupport/SMECoreB1Program' # 502
    vulnerabilityThresholdResult: 'FAILURE'
    waitForResultsEnabled: true
  whitesourceExecuteScan:
    userTokenCredentialsId: cdc-tools-chrome-extension-whitesource
    productName: cdc-tools-chrome-extension
    projectName: sap-customer-data-cloud-toolkit
    serviceUrl: 'https://sap.whitesourcesoftware.com/api/v1.4'
  sonarExecuteScan:
    serverUrl: 'https://sonar.tools.sap'
    sonarTokenCredentialsId: 'hyperspace-sonar-i545698'
    sonarVaultSecretName: 'GROUP-SECRETS/sonar-cdc-sonar-token'
    waitForQualityGate: true
