/*
 * Copyright: Copyright 2023 SAP SE or an SAP affiliate company and cdc-tools-chrome-extension contributors
 * License: Apache-2.0
 */
import {
  profileBranches,
  dataBranches,
  subscriptionsBranches,
  internalBranches,
  addressesBranches,
  preferencesBranches,
  communicationsBranches,
  passwordBranches,
} from './mainDataSet'
export const expectedFullAccount = [
  { id: 'uid', name: 'uid', value: true, branches: [], mandatory: true },
  { id: 'profile', name: 'profile', value: false, branches: profileBranches, switchId: 'object' },
  { id: 'data', name: 'data', value: false, branches: dataBranches, switchId: 'object' },
  { id: 'subscriptions', name: 'subscriptions', value: false, branches: subscriptionsBranches, switchId: 'object' },
  { id: 'internal', name: 'internal', value: false, branches: internalBranches, switchId: 'object' },
  { id: 'addresses', name: 'addresses', value: false, branches: addressesBranches, switchId: 'object' },
  { id: 'preferences', name: 'preferences', value: false, branches: preferencesBranches },
  { id: 'communications', name: 'communications', value: false, branches: communicationsBranches },
  { id: 'password', name: 'password', value: false, branches: passwordBranches },
  { id: 'phoneNumber', name: 'phoneNumber', value: false, branches: [] },
  {
    id: 'loginIds',
    name: 'loginIds',
    value: false,
    branches: [
      { id: 'loginIds.username', name: 'username', value: false, branches: [] },
      { id: 'loginIds.email', name: 'email', value: false, branches: [] },
      { id: 'loginIds.unverifiedEmail', name: 'unverifiedEmail', value: false, branches: [] },
    ],
  },
  { id: 'isActive', name: 'isActive', value: false, branches: [] },
  { id: 'isRegistered', name: 'isRegistered', value: false, branches: [] },
  { id: 'isVerified', name: 'isVerified', value: false, branches: [] },
  { id: 'verified', name: 'verified', value: false, branches: [] },
  { id: 'regSource', name: 'regSource', value: false, branches: [] },
  { id: 'dataCenter', name: 'dataCenter', value: false, branches: [] },
  { id: 'registered', name: 'registered', value: false, branches: [] },
  { id: 'context', name: 'context', value: false, branches: [] },
  { id: 'lang', name: 'lang', value: false, branches: [] },
]
export const expectedLiteAccount = [
  { id: 'email', name: 'email', value: true, branches: [], mandatory: true },
  { id: 'profile', name: 'profile', value: false, branches: profileBranches, switchId: 'object' },
  { id: 'data', name: 'data', value: false, branches: dataBranches, switchId: 'object' },
  { id: 'subscriptions', name: 'subscriptions', value: false, branches: subscriptionsBranches, switchId: 'object' },
  { id: 'preferences', name: 'preferences', value: false, branches: preferencesBranches },
  { id: 'context', name: 'context', value: false, branches: [] },
]
export const expectedOptionsFromTree = [
  {
    id: 'uid',
    name: 'uid',
    value: true,
    branches: [],
    mandatory: true,
  },
  {
    id: 'profile',
    name: 'profile',
    value: true,
    branches: [
      {
        id: 'profile.photoURL',
        name: 'photoURL',
        value: true,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.oidcData',
        name: 'oidcData',
        value: true,
        branches: [
          {
            id: 'profile.oidcData.address',
            name: 'address',
            value: false,
            branches: [
              {
                id: 'profile.oidcData.address.locality',
                name: 'locality',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.oidcData.address.formatted',
                name: 'formatted',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.oidcData.address.country',
                name: 'country',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.oidcData.address.region',
                name: 'region',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.oidcData.address.postal_code',
                name: 'postal_code',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.oidcData.address.street_address',
                name: 'street_address',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.website',
            name: 'website',
            value: true,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.phone_number_verified',
            name: 'phone_number_verified',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.phone_number',
            name: 'phone_number',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.locale',
            name: 'locale',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.updated_at',
            name: 'updated_at',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.name',
            name: 'name',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.email_verified',
            name: 'email_verified',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.middle_name',
            name: 'middle_name',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.zoneinfo',
            name: 'zoneinfo',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.favorites',
        name: 'favorites',
        value: false,
        branches: [
          {
            id: 'profile.favorites.activities',
            name: 'activities',
            value: false,
            branches: [
              {
                id: 'profile.favorites.activities.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.activities.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.activities.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.movies',
            name: 'movies',
            value: false,
            branches: [
              {
                id: 'profile.favorites.movies.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.movies.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.movies.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.music',
            name: 'music',
            value: false,
            branches: [
              {
                id: 'profile.favorites.music.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.music.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.music.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.television',
            name: 'television',
            value: false,
            branches: [
              {
                id: 'profile.favorites.television.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.television.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.television.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.interests',
            name: 'interests',
            value: false,
            branches: [
              {
                id: 'profile.favorites.interests.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.interests.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.interests.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.books',
            name: 'books',
            value: false,
            branches: [
              {
                id: 'profile.favorites.books.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.books.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.books.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.certifications',
        name: 'certifications',
        value: false,
        branches: [
          {
            id: 'profile.certifications.number',
            name: 'number',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.certifications.endDate',
            name: 'endDate',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.certifications.name',
            name: 'name',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.certifications.startDate',
            name: 'startDate',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.certifications.authority',
            name: 'authority',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.religion',
        name: 'religion',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.likes',
        name: 'likes',
        value: false,
        branches: [
          {
            id: 'profile.likes.timestamp',
            name: 'timestamp',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.likes.id',
            name: 'id',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.likes.name',
            name: 'name',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.likes.time',
            name: 'time',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.likes.category',
            name: 'category',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.birthYear',
        name: 'birthYear',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.phones',
        name: 'phones',
        value: false,
        branches: [
          {
            id: 'profile.phones.type',
            name: 'type',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.phones.number',
            name: 'number',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.phones.default',
            name: 'default',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.patents',
        name: 'patents',
        value: false,
        branches: [
          {
            id: 'profile.patents.date',
            name: 'date',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.status',
            name: 'status',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.url',
            name: 'url',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.office',
            name: 'office',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.summary',
            name: 'summary',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.number',
            name: 'number',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.title',
            name: 'title',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.languages',
        name: 'languages',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.work',
        name: 'work',
        value: false,
        branches: [
          {
            id: 'profile.work.startDate',
            name: 'startDate',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.description',
            name: 'description',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.title',
            name: 'title',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.industry',
            name: 'industry',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.location',
            name: 'location',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.endDate',
            name: 'endDate',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.company',
            name: 'company',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.companyID',
            name: 'companyID',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.companySize',
            name: 'companySize',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.isCurrent',
            name: 'isCurrent',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.industry',
        name: 'industry',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.firstName',
        name: 'firstName',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.publications',
        name: 'publications',
        value: false,
        branches: [
          {
            id: 'profile.publications.publisher',
            name: 'publisher',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.publications.url',
            name: 'url',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.publications.title',
            name: 'title',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.publications.summary',
            name: 'summary',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.publications.date',
            name: 'date',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.city',
        name: 'city',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.verified',
        name: 'verified',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.gender',
        name: 'gender',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.hometown',
        name: 'hometown',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.followersCount',
        name: 'followersCount',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.birthDay',
        name: 'birthDay',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.interests',
        name: 'interests',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.lastName',
        name: 'lastName',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.locale',
        name: 'locale',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.skills',
        name: 'skills',
        value: false,
        branches: [
          {
            id: 'profile.skills.level',
            name: 'level',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.skills.skill',
            name: 'skill',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.skills.years',
            name: 'years',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.relationshipStatus',
        name: 'relationshipStatus',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.name',
        name: 'name',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.education',
        name: 'education',
        value: false,
        branches: [
          {
            id: 'profile.education.endYear',
            name: 'endYear',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.education.startYear',
            name: 'startYear',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.education.school',
            name: 'school',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.education.schoolType',
            name: 'schoolType',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.education.fieldOfStudy',
            name: 'fieldOfStudy',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.education.degree',
            name: 'degree',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.honors',
        name: 'honors',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.age',
        name: 'age',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.bio',
        name: 'bio',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.state',
        name: 'state',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.lastLoginLocation',
        name: 'lastLoginLocation',
        value: false,
        branches: [
          {
            id: 'profile.lastLoginLocation.coordinates',
            name: 'coordinates',
            value: false,
            branches: [
              {
                id: 'profile.lastLoginLocation.coordinates.lat',
                name: 'lat',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.lastLoginLocation.coordinates.lon',
                name: 'lon',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.lastLoginLocation.state',
            name: 'state',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.lastLoginLocation.city',
            name: 'city',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.lastLoginLocation.country',
            name: 'country',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.professionalHeadline',
        name: 'professionalHeadline',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.email',
        name: 'email',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.politicalView',
        name: 'politicalView',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.educationLevel',
        name: 'educationLevel',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.timezone',
        name: 'timezone',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.address',
        name: 'address',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.proxyemail',
        name: 'proxyemail',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.followingCount',
        name: 'followingCount',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.profileURL',
        name: 'profileURL',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.thumbnailURL',
        name: 'thumbnailURL',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.specialities',
        name: 'specialities',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.interestedIn',
        name: 'interestedIn',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.birthMonth',
        name: 'birthMonth',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.nickname',
        name: 'nickname',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.username',
        name: 'username',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.zip',
        name: 'zip',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.country',
        name: 'country',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.activities',
        name: 'activities',
        value: false,
        branches: [],
        switchId: 'object',
      },
    ],
    switchId: 'object',
  },
  {
    id: 'data',
    name: 'data',
    value: true,
    branches: [
      {
        id: 'data.loyalty',
        name: 'loyalty',
        value: true,
        branches: [
          {
            id: 'data.loyalty.rewardPoints',
            name: 'rewardPoints',
            value: true,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'data.loyalty.rewardRedemption',
            name: 'rewardRedemption',
            value: false,
            branches: [
              {
                id: 'data.loyalty.rewardRedemption.redemptionDate',
                name: 'redemptionDate',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'data.loyalty.rewardRedemption.redemptionPoint',
                name: 'redemptionPoint',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'data.loyalty.loyaltyStatus',
            name: 'loyaltyStatus',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'data.loyalty.rewardAmount',
            name: 'rewardAmount',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'data.vehicle',
        name: 'vehicle',
        value: false,
        branches: [
          {
            id: 'data.vehicle.model',
            name: 'model',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'data.vehicle.vin',
            name: 'vin',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'data.vehicle.registrationDate',
            name: 'registrationDate',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'data.crm',
        name: 'crm',
        value: false,
        branches: [
          {
            id: 'data.crm.isProspect',
            name: 'isProspect',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'data.crm.abcClassification',
            name: 'abcClassification',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'data.subscribe',
        name: 'subscribe',
        value: true,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'data.terms',
        name: 'terms',
        value: false,
        branches: [],
        switchId: 'object',
      },
    ],
    switchId: 'object',
  },
  {
    id: 'subscriptions',
    name: 'subscriptions',
    value: true,
    branches: [
      {
        id: 'subscriptions.newsletter.commercial',
        name: 'newsletter.commercial',
        value: true,
        branches: [
          {
            id: 'subscriptions.newsletter.commercial.isSubscribed',
            name: 'isSubscribed',
            value: true,
            branches: [],
            mandatory: true,
          },
          {
            id: 'subscriptions.newsletter.commercial.tags',
            name: 'tags',
            value: true,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.commercial.lastUpdatedSubscriptionState',
            name: 'lastUpdatedSubscriptionState',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.commercial.doubleOptIn',
            name: 'doubleOptIn',
            value: false,
            branches: [
              {
                id: 'subscriptions.newsletter.commercial.doubleOptIn.isExternallyVerified',
                name: 'isExternallyVerified',
                value: false,
                branches: [],
              },
            ],
          },
        ],
        switchId: 'object',
      },
      {
        id: 'subscriptions.newsletter.passenger',
        name: 'newsletter.passenger',
        value: false,
        branches: [
          {
            id: 'subscriptions.newsletter.passenger.isSubscribed',
            name: 'isSubscribed',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.passenger.tags',
            name: 'tags',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.passenger.lastUpdatedSubscriptionState',
            name: 'lastUpdatedSubscriptionState',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.passenger.doubleOptIn',
            name: 'doubleOptIn',
            value: false,
            branches: [
              {
                id: 'subscriptions.newsletter.passenger.doubleOptIn.isExternallyVerified',
                name: 'isExternallyVerified',
                value: false,
                branches: [],
              },
            ],
          },
        ],
        switchId: 'object',
      },
      {
        id: 'subscriptions.promotion',
        name: 'promotion',
        value: false,
        branches: [
          {
            id: 'subscriptions.promotion.isSubscribed',
            name: 'isSubscribed',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.promotion.tags',
            name: 'tags',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.promotion.lastUpdatedSubscriptionState',
            name: 'lastUpdatedSubscriptionState',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.promotion.doubleOptIn',
            name: 'doubleOptIn',
            value: false,
            branches: [
              {
                id: 'subscriptions.promotion.doubleOptIn.isExternallyVerified',
                name: 'isExternallyVerified',
                value: false,
                branches: [],
              },
            ],
          },
        ],
        switchId: 'object',
      },
    ],
    switchId: 'object',
  },
  {
    id: 'internal',
    name: 'internal',
    value: true,
    branches: [
      {
        id: 'internal.s4hana',
        name: 's4hana',
        value: true,
        branches: [
          {
            id: 'internal.s4hana.s4Id',
            name: 's4Id',
            value: true,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'internal.crm',
        name: 'crm',
        value: false,
        branches: [
          {
            id: 'internal.crm.crmGuid',
            name: 'crmGuid',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'internal.crm.crmId',
            name: 'crmId',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'internal.madId',
        name: 'madId',
        value: true,
        branches: [],
        switchId: 'object',
      },
    ],
    switchId: 'object',
  },
  {
    id: 'addresses',
    name: 'addresses',
    value: true,
    branches: [
      {
        id: 'addresses.soldTo',
        name: 'soldTo',
        value: true,
        branches: [
          {
            id: 'addresses.soldTo.entrance',
            name: 'entrance',
            value: true,
            branches: [],
          },
          {
            id: 'addresses.soldTo.countryISOCode3',
            name: 'countryISOCode3',
            value: true,
            branches: [],
          },
          {
            id: 'addresses.soldTo.houseNumber',
            name: 'houseNumber',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.soldTo.city',
            name: 'city',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.soldTo.postOfficeBox',
            name: 'postOfficeBox',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.soldTo.zipCode',
            name: 'zipCode',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.soldTo.building',
            name: 'building',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.soldTo.apartment',
            name: 'apartment',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.soldTo.neighborhood',
            name: 'neighborhood',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.soldTo.street',
            name: 'street',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.soldTo.floor',
            name: 'floor',
            value: false,
            branches: [],
          },
        ],
      },
      {
        id: 'addresses.shipTo',
        name: 'shipTo',
        value: true,
        branches: [
          {
            id: 'addresses.shipTo.apartment',
            name: 'apartment',
            value: true,
            branches: [],
          },
          {
            id: 'addresses.shipTo.city',
            name: 'city',
            value: true,
            branches: [],
          },
          {
            id: 'addresses.shipTo.floor',
            name: 'floor',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.shipTo.street',
            name: 'street',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.shipTo.postOfficeBox',
            name: 'postOfficeBox',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.shipTo.countryISOCode3',
            name: 'countryISOCode3',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.shipTo.building',
            name: 'building',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.shipTo.houseNumber',
            name: 'houseNumber',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.shipTo.entrance',
            name: 'entrance',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.shipTo.zipCode',
            name: 'zipCode',
            value: false,
            branches: [],
          },
          {
            id: 'addresses.shipTo.neighborhood',
            name: 'neighborhood',
            value: false,
            branches: [],
          },
        ],
      },
    ],
    switchId: 'object',
  },
  {
    id: 'preferences',
    name: 'preferences',
    value: true,
    branches: [
      {
        id: 'preferences.terms',
        name: 'terms',
        value: true,
        branches: [
          {
            id: 'preferences.terms.sap',
            name: 'sap',
            value: true,
            branches: [
              {
                id: 'preferences.terms.sap.isConsentGranted',
                name: 'isConsentGranted',
                value: true,
                branches: [],
                mandatory: true,
              },
              {
                id: 'preferences.terms.sap.actionTimestamp',
                name: 'actionTimestamp',
                value: true,
                branches: [],
              },
              {
                id: 'preferences.terms.sap.lastConsentModified',
                name: 'lastConsentModified',
                value: false,
                branches: [],
              },
              {
                id: 'preferences.terms.sap.docVersion',
                name: 'docVersion',
                value: false,
                branches: [],
              },
              {
                id: 'preferences.terms.sap.docDate',
                name: 'docDate',
                value: false,
                branches: [],
              },
              {
                id: 'preferences.terms.sap.tags',
                name: 'tags',
                value: false,
                branches: [],
              },
              {
                id: 'preferences.terms.sap.entitlements',
                name: 'entitlements',
                value: false,
                branches: [],
              },
            ],
          },
        ],
      },
      {
        id: 'preferences.privacy',
        name: 'privacy',
        value: false,
        branches: [
          {
            id: 'preferences.privacy.sap',
            name: 'sap',
            value: false,
            branches: [
              {
                id: 'preferences.privacy.sap.isConsentGranted',
                name: 'isConsentGranted',
                value: false,
                branches: [],
                mandatory: false,
              },
              {
                id: 'preferences.privacy.sap.actionTimestamp',
                name: 'actionTimestamp',
                value: false,
                branches: [],
              },
              {
                id: 'preferences.privacy.sap.lastConsentModified',
                name: 'lastConsentModified',
                value: false,
                branches: [],
              },
              {
                id: 'preferences.privacy.sap.docVersion',
                name: 'docVersion',
                value: false,
                branches: [],
              },
              {
                id: 'preferences.privacy.sap.docDate',
                name: 'docDate',
                value: false,
                branches: [],
              },
              {
                id: 'preferences.privacy.sap.tags',
                name: 'tags',
                value: false,
                branches: [],
              },
              {
                id: 'preferences.privacy.sap.entitlements',
                name: 'entitlements',
                value: false,
                branches: [],
              },
            ],
          },
        ],
      },
      {
        id: 'preferences.cookie',
        name: 'cookie',
        value: false,
        branches: [
          {
            id: 'preferences.cookie.isConsentGranted',
            name: 'isConsentGranted',
            value: false,
            branches: [],
            mandatory: false,
          },
          {
            id: 'preferences.cookie.actionTimestamp',
            name: 'actionTimestamp',
            value: false,
            branches: [],
          },
          {
            id: 'preferences.cookie.lastConsentModified',
            name: 'lastConsentModified',
            value: false,
            branches: [],
          },
          {
            id: 'preferences.cookie.docVersion',
            name: 'docVersion',
            value: false,
            branches: [],
          },
          {
            id: 'preferences.cookie.docDate',
            name: 'docDate',
            value: false,
            branches: [],
          },
          {
            id: 'preferences.cookie.tags',
            name: 'tags',
            value: false,
            branches: [],
          },
          {
            id: 'preferences.cookie.entitlements',
            name: 'entitlements',
            value: false,
            branches: [],
          },
        ],
      },
    ],
  },
  {
    id: 'communications',
    name: 'communications',
    value: true,
    branches: [
      {
        id: 'C_Email',
        name: 'C_Email',
        value: false,
        branches: [
          {
            id: 'communications.C_Email.status',
            name: 'status',
            value: false,
            branches: [],
            mandatory: false,
          },
        ],
      },
      {
        id: 'T_Email',
        name: 'T_Email',
        value: false,
        branches: [
          {
            id: 'communications.T_Email.status',
            name: 'status',
            value: false,
            branches: [],
            mandatory: false,
          },
        ],
      },
      {
        id: 'C_mobileApp',
        name: 'C_mobileApp',
        value: true,
        branches: [
          {
            id: 'communications.C_mobileApp.status',
            name: 'status',
            value: true,
            branches: [],
            mandatory: true,
          },
          {
            id: 'communications.C_mobileApp.optIn.acceptanceLocation',
            name: 'acceptanceLocation',
            value: true,
            branches: [],
          },
          {
            id: 'communications.C_mobileApp.optIn.sourceApplication',
            name: 'sourceApplication',
            value: false,
            branches: [],
          },
        ],
      },
      {
        id: 'C_whatsApp',
        name: 'C_whatsApp',
        value: false,
        branches: [
          {
            id: 'communications.C_whatsApp.status',
            name: 'status',
            value: false,
            branches: [],
          },
        ],
      },
      {
        id: 'T_SMS',
        name: 'T_SMS',
        value: false,
        branches: [
          {
            id: 'communications.T_SMS.status',
            name: 'status',
            value: false,
            branches: [],
          },
        ],
      },
      {
        id: 'C_SMS',
        name: 'C_SMS',
        value: false,
        branches: [
          {
            id: 'communications.C_SMS.status',
            name: 'status',
            value: false,
            branches: [],
          },
          {
            id: 'communications.C_SMS.optIn.acceptanceLocation',
            name: 'acceptanceLocation',
            value: false,
            branches: [],
          },
        ],
      },
    ],
  },
  {
    id: 'password',
    name: 'password',
    value: true,
    branches: [
      {
        id: 'password.compoundHashedPassword',
        name: 'compoundHashedPassword',
        value: true,
        branches: [],
      },
      {
        id: 'password.hashedPassword',
        name: 'hashedPassword',
        value: true,
        branches: [],
      },
      {
        id: 'password.hashSettings',
        name: 'hashSettings',
        value: false,
        branches: [
          {
            id: 'password.hashSettings.algorithm',
            name: 'algorithm',
            value: false,
            branches: [],
          },
          {
            id: 'password.hashSettings.salt',
            name: 'salt',
            value: false,
            branches: [],
          },
          {
            id: 'password.hashSettings.rounds',
            name: 'rounds',
            value: false,
            branches: [],
          },
          {
            id: 'password.hashSettings.format',
            name: 'format',
            value: false,
            branches: [],
          },
          {
            id: 'password.hashSettings.binaryFormat',
            name: 'binaryFormat',
            value: false,
            branches: [],
          },
          {
            id: 'password.hashSettings.URL',
            name: 'URL',
            value: false,
            branches: [],
          },
        ],
      },
      {
        id: 'password.secretQuestionAndAnswer',
        name: 'secretQuestionAndAnswer',
        value: false,
        branches: [
          {
            id: 'password.secretQuestionAndAnswer.secretQuestion',
            name: 'secretQuestion',
            value: false,
            branches: [],
          },
          {
            id: 'password.secretQuestionAndAnswer.secretAnswer',
            name: 'secretAnswer',
            value: false,
            branches: [],
          },
        ],
      },
    ],
  },
  {
    id: 'phoneNumber',
    name: 'phoneNumber',
    value: true,
    branches: [],
  },
  {
    id: 'loginIds',
    name: 'loginIds',
    value: true,
    branches: [
      {
        id: 'loginIds.username',
        name: 'username',
        value: true,
        branches: [],
      },
      {
        id: 'loginIds.email',
        name: 'email',
        value: true,
        branches: [],
      },
      {
        id: 'loginIds.unverifiedEmail',
        name: 'unverifiedEmail',
        value: false,
        branches: [],
      },
    ],
  },
  {
    id: 'isActive',
    name: 'isActive',
    value: true,
    branches: [],
  },
  {
    id: 'isRegistered',
    name: 'isRegistered',
    value: false,
    branches: [],
  },
  {
    id: 'isVerified',
    name: 'isVerified',
    value: false,
    branches: [],
  },
  {
    id: 'verified',
    name: 'verified',
    value: false,
    branches: [],
  },
  {
    id: 'regSource',
    name: 'regSource',
    value: false,
    branches: [],
  },
  {
    id: 'dataCenter',
    name: 'dataCenter',
    value: false,
    branches: [],
  },
  {
    id: 'registered',
    name: 'registered',
    value: false,
    branches: [],
  },
  {
    id: 'context',
    name: 'context',
    value: false,
    branches: [],
  },
  {
    id: 'lang',
    name: 'lang',
    value: false,
    branches: [],
  },
]

export const expectedResultFromTree = [
  'uid',
  'phoneNumber',
  'loginIds.username',
  'loginIds.email',
  'isActive',
  'profile.photoURL',
  'profile.oidcData.website',
  'data.loyalty.rewardPoints',
  'data.subscribe',
  'subscriptions.newsletter.commercial.isSubscribed',
  'subscriptions.newsletter.commercial.tags',
  'internal.s4hana.s4Id',
  'internal.madId',
  'addresses.soldTo.entrance',
  'addresses.soldTo.countryISOCode3',
  'addresses.shipTo.apartment',
  'addresses.shipTo.city',
  'preferences.terms.sap.isConsentGranted',
  'preferences.terms.sap.actionTimestamp',
  'communications.C_mobileApp.status',
  'communications.C_mobileApp.optIn.acceptanceLocation',
  'password.compoundHashedPassword',
  'password.hashedPassword',
]
