export const expectedSchemaResponse = {
  callId: 'e67ef8a0e6314103a7b2ef4bdda4da69',
  statusCode: 200,
  statusReason: 'OK',
  time: '2024-12-05T18:17:23.716Z',
  profileSchema: {
    fields: {
      photoURL: {
        required: false,
        type: 'string',
      },
      'oidcData.address.locality': {
        required: false,
        type: 'string',
      },
      'favorites.activities.category': {
        required: false,
        type: 'string',
      },
      'certifications.number': {
        required: false,
        type: 'basic-string',
      },
      religion: {
        required: false,
        type: 'string',
      },
      'favorites.movies.name': {
        required: false,
        type: 'string',
      },
      'oidcData.address.formatted': {
        required: false,
        type: 'string',
      },
    },
    dynamicSchema: false,
  },
  dataSchema: {
    fields: {
      'loyalty.rewardPoints': {
        required: false,
        type: 'integer',
      },
      'vehicle.model': {
        required: false,
        type: 'string',
      },
      'crm.isProspect': {
        required: false,
        type: 'boolean',
      },
      'loyalty.rewardRedemption.redemptionDate': {
        required: false,
        type: 'date',
      },
      subscribe: {
        required: false,
        type: 'boolean',
      },
      'vehicle.vin': {
        required: false,
        type: 'string',
      },
      'loyalty.loyaltyStatus': {
        required: false,
        type: 'string',
      },
      'loyalty.rewardRedemption.redemptionPoint': {
        required: false,
        type: 'integer',
      },
      terms: {
        required: false,
        type: 'boolean',
      },
      'crm.abcClassification': {
        required: false,
        type: 'string',
      },
      'loyalty.rewardAmount': {
        required: false,
        type: 'float',
      },
      'vehicle.registrationDate': {
        required: false,
        type: 'date',
      },
    },
    dynamicSchema: false,
  },
  subscriptionsSchema: {
    fields: {
      'newsletter.commercial': {},
      'newsletter.passenger': {},
      promotion: {},
    },
  },
  internalSchema: {
    fields: {
      's4hana.s4Id': {
        required: false,
        type: 'string',
      },
      'crm.crmGuid': {
        required: false,
        type: 'string',
      },
      madId: {
        required: false,
        type: 'string',
      },
      'crm.crmId': {
        required: false,
        type: 'string',
      },
    },
    dynamicSchema: false,
  },
  addressesSchema: {
    fields: {
      soldTo: {
        entrance: {
          type: 'string',
          required: false,
          writeAccess: 'clientModify',
          allowNull: true,
          format: null,
          encrypt: 'AES',
        },
      },
      shipTo: {
        apartment: {
          type: 'string',
          required: false,
          writeAccess: 'clientModify',
          allowNull: true,
          format: null,
          encrypt: 'AES',
        },
      },
    },
  },
}

export const expectedLiteSchemaResponse = [
  {
    id: 'profile',
    name: 'profile',
    value: false,
    branches: [
      {
        id: 'profile.photoURL',
        name: 'photoURL',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.oidcData',
        name: 'oidcData',
        value: false,
        branches: [
          {
            id: 'profile.oidcData.address',
            name: 'address',
            value: false,
            branches: [
              {
                id: 'profile.oidcData.address.locality',
                name: 'locality',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.oidcData.address.formatted',
                name: 'formatted',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.oidcData.address.country',
                name: 'country',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.oidcData.address.region',
                name: 'region',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.oidcData.address.postal_code',
                name: 'postal_code',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.oidcData.address.street_address',
                name: 'street_address',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.website',
            name: 'website',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.phone_number_verified',
            name: 'phone_number_verified',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.phone_number',
            name: 'phone_number',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.locale',
            name: 'locale',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.updated_at',
            name: 'updated_at',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.name',
            name: 'name',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.email_verified',
            name: 'email_verified',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.middle_name',
            name: 'middle_name',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.oidcData.zoneinfo',
            name: 'zoneinfo',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.favorites',
        name: 'favorites',
        value: false,
        branches: [
          {
            id: 'profile.favorites.activities',
            name: 'activities',
            value: false,
            branches: [
              {
                id: 'profile.favorites.activities.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.activities.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.activities.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.movies',
            name: 'movies',
            value: false,
            branches: [
              {
                id: 'profile.favorites.movies.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.movies.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.movies.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.music',
            name: 'music',
            value: false,
            branches: [
              {
                id: 'profile.favorites.music.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.music.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.music.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.television',
            name: 'television',
            value: false,
            branches: [
              {
                id: 'profile.favorites.television.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.television.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.television.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.interests',
            name: 'interests',
            value: false,
            branches: [
              {
                id: 'profile.favorites.interests.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.interests.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.interests.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.books',
            name: 'books',
            value: false,
            branches: [
              {
                id: 'profile.favorites.books.category',
                name: 'category',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.books.name',
                name: 'name',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.favorites.books.id',
                name: 'id',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.certifications',
        name: 'certifications',
        value: false,
        branches: [
          {
            id: 'profile.certifications.number',
            name: 'number',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.certifications.endDate',
            name: 'endDate',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.certifications.name',
            name: 'name',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.certifications.startDate',
            name: 'startDate',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.certifications.authority',
            name: 'authority',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.religion',
        name: 'religion',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.likes',
        name: 'likes',
        value: false,
        branches: [
          {
            id: 'profile.likes.timestamp',
            name: 'timestamp',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.likes.id',
            name: 'id',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.likes.name',
            name: 'name',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.likes.time',
            name: 'time',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.likes.category',
            name: 'category',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.birthYear',
        name: 'birthYear',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.phones',
        name: 'phones',
        value: false,
        branches: [
          {
            id: 'profile.phones.type',
            name: 'type',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.phones.number',
            name: 'number',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.phones.default',
            name: 'default',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.patents',
        name: 'patents',
        value: false,
        branches: [
          {
            id: 'profile.patents.date',
            name: 'date',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.status',
            name: 'status',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.url',
            name: 'url',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.office',
            name: 'office',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.summary',
            name: 'summary',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.number',
            name: 'number',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.patents.title',
            name: 'title',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.languages',
        name: 'languages',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.work',
        name: 'work',
        value: false,
        branches: [
          {
            id: 'profile.work.startDate',
            name: 'startDate',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.description',
            name: 'description',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.title',
            name: 'title',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.industry',
            name: 'industry',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.location',
            name: 'location',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.endDate',
            name: 'endDate',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.company',
            name: 'company',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.companyID',
            name: 'companyID',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.companySize',
            name: 'companySize',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.work.isCurrent',
            name: 'isCurrent',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.industry',
        name: 'industry',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.firstName',
        name: 'firstName',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.publications',
        name: 'publications',
        value: false,
        branches: [
          {
            id: 'profile.publications.publisher',
            name: 'publisher',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.publications.url',
            name: 'url',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.publications.title',
            name: 'title',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.publications.summary',
            name: 'summary',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.publications.date',
            name: 'date',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.city',
        name: 'city',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.verified',
        name: 'verified',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.gender',
        name: 'gender',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.hometown',
        name: 'hometown',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.followersCount',
        name: 'followersCount',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.birthDay',
        name: 'birthDay',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.interests',
        name: 'interests',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.lastName',
        name: 'lastName',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.locale',
        name: 'locale',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.skills',
        name: 'skills',
        value: false,
        branches: [
          {
            id: 'profile.skills.level',
            name: 'level',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.skills.skill',
            name: 'skill',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.skills.years',
            name: 'years',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.relationshipStatus',
        name: 'relationshipStatus',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.name',
        name: 'name',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.education',
        name: 'education',
        value: false,
        branches: [
          {
            id: 'profile.education.endYear',
            name: 'endYear',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.education.startYear',
            name: 'startYear',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.education.school',
            name: 'school',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.education.schoolType',
            name: 'schoolType',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.education.fieldOfStudy',
            name: 'fieldOfStudy',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.education.degree',
            name: 'degree',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.honors',
        name: 'honors',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.age',
        name: 'age',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.bio',
        name: 'bio',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.state',
        name: 'state',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.lastLoginLocation',
        name: 'lastLoginLocation',
        value: false,
        branches: [
          {
            id: 'profile.lastLoginLocation.coordinates',
            name: 'coordinates',
            value: false,
            branches: [
              {
                id: 'profile.lastLoginLocation.coordinates.lat',
                name: 'lat',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'profile.lastLoginLocation.coordinates.lon',
                name: 'lon',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'profile.lastLoginLocation.state',
            name: 'state',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.lastLoginLocation.city',
            name: 'city',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'profile.lastLoginLocation.country',
            name: 'country',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.professionalHeadline',
        name: 'professionalHeadline',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.politicalView',
        name: 'politicalView',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.educationLevel',
        name: 'educationLevel',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.timezone',
        name: 'timezone',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.address',
        name: 'address',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.proxyemail',
        name: 'proxyemail',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.followingCount',
        name: 'followingCount',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.profileURL',
        name: 'profileURL',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.thumbnailURL',
        name: 'thumbnailURL',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.specialities',
        name: 'specialities',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.interestedIn',
        name: 'interestedIn',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.birthMonth',
        name: 'birthMonth',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.nickname',
        name: 'nickname',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.username',
        name: 'username',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.zip',
        name: 'zip',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.country',
        name: 'country',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'profile.activities',
        name: 'activities',
        value: false,
        branches: [],
        switchId: 'object',
      },
    ],
    switchId: 'object',
  },
  {
    id: 'data',
    name: 'data',
    value: false,
    branches: [
      {
        id: 'data.loyalty',
        name: 'loyalty',
        value: false,
        branches: [
          {
            id: 'data.loyalty.rewardPoints',
            name: 'rewardPoints',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'data.loyalty.rewardRedemption',
            name: 'rewardRedemption',
            value: false,
            branches: [
              {
                id: 'data.loyalty.rewardRedemption.redemptionDate',
                name: 'redemptionDate',
                value: false,
                branches: [],
                switchId: 'object',
              },
              {
                id: 'data.loyalty.rewardRedemption.redemptionPoint',
                name: 'redemptionPoint',
                value: false,
                branches: [],
                switchId: 'object',
              },
            ],
            switchId: 'object',
          },
          {
            id: 'data.loyalty.loyaltyStatus',
            name: 'loyaltyStatus',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'data.loyalty.rewardAmount',
            name: 'rewardAmount',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'data.vehicle',
        name: 'vehicle',
        value: false,
        branches: [
          {
            id: 'data.vehicle.model',
            name: 'model',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'data.vehicle.vin',
            name: 'vin',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'data.vehicle.registrationDate',
            name: 'registrationDate',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'data.crm',
        name: 'crm',
        value: false,
        branches: [
          {
            id: 'data.crm.isProspect',
            name: 'isProspect',
            value: false,
            branches: [],
            switchId: 'object',
          },
          {
            id: 'data.crm.abcClassification',
            name: 'abcClassification',
            value: false,
            branches: [],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'data.subscribe',
        name: 'subscribe',
        value: false,
        branches: [],
        switchId: 'object',
      },
      {
        id: 'data.terms',
        name: 'terms',
        value: false,
        branches: [],
        switchId: 'object',
      },
    ],
    switchId: 'object',
  },
  {
    id: 'subscriptions',
    name: 'subscriptions',
    value: false,
    branches: [
      {
        id: 'subscriptions.newsletter.commercial',
        name: 'newsletter.commercial',
        value: false,
        branches: [
          {
            id: 'subscriptions.newsletter.commercial.isSubscribed',
            name: 'isSubscribed',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.commercial.tags',
            name: 'tags',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.commercial.lastUpdatedSubscriptionState',
            name: 'lastUpdatedSubscriptionState',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.commercial.doubleOptIn',
            name: 'doubleOptIn',
            value: false,
            branches: [
              {
                id: 'subscriptions.newsletter.commercial.doubleOptIn.isExternallyVerified',
                name: 'isExternallyVerified',
                value: false,
                branches: [],
              },
            ],
          },
        ],
        switchId: 'object',
      },
      {
        id: 'subscriptions.newsletter.passenger',
        name: 'newsletter.passenger',
        value: false,
        branches: [
          {
            id: 'subscriptions.newsletter.passenger.isSubscribed',
            name: 'isSubscribed',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.passenger.tags',
            name: 'tags',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.passenger.lastUpdatedSubscriptionState',
            name: 'lastUpdatedSubscriptionState',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.newsletter.passenger.doubleOptIn',
            name: 'doubleOptIn',
            value: false,
            branches: [
              {
                id: 'subscriptions.newsletter.passenger.doubleOptIn.isExternallyVerified',
                name: 'isExternallyVerified',
                value: false,
                branches: [],
              },
            ],
          },
        ],
        switchId: 'object',
      },
      {
        id: 'subscriptions.promotion',
        name: 'promotion',
        value: false,
        branches: [
          {
            id: 'subscriptions.promotion.isSubscribed',
            name: 'isSubscribed',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.promotion.tags',
            name: 'tags',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.promotion.lastUpdatedSubscriptionState',
            name: 'lastUpdatedSubscriptionState',
            value: false,
            branches: [],
          },
          {
            id: 'subscriptions.promotion.doubleOptIn',
            name: 'doubleOptIn',
            value: false,
            branches: [
              {
                id: 'subscriptions.promotion.doubleOptIn.isExternallyVerified',
                name: 'isExternallyVerified',
                value: false,
                branches: [],
              },
            ],
          },
        ],
        switchId: 'object',
      },
    ],
    switchId: 'object',
  },
]

export const expectedSchemaResponseCleaned = {
  callId: 'e67ef8a0e6314103a7b2ef4bdda4da69',
  statusCode: 200,
  statusReason: 'OK',
  time: '2024-12-05T18:17:23.716Z',
  profileSchema: {
    fields: {
      photoURL: {
        required: false,
        type: 'string',
      },
      'oidcData.address.locality': {
        required: false,
        type: 'string',
      },
      'favorites.activities.category': {
        required: false,
        type: 'string',
      },
      'certifications.number': {
        required: false,
        type: 'basic-string',
      },
      religion: {
        required: false,
        type: 'string',
      },
      'favorites.movies.name': {
        required: false,
        type: 'string',
      },
      'oidcData.address.formatted': {
        required: false,
        type: 'string',
      },
    },
    dynamicSchema: false,
  },
  dataSchema: {
    fields: {
      'loyalty.rewardPoints': {
        required: false,
        type: 'integer',
      },
      'vehicle.model': {
        required: false,
        type: 'string',
      },
      'crm.isProspect': {
        required: false,
        type: 'boolean',
      },
      'loyalty.rewardRedemption.redemptionDate': {
        required: false,
        type: 'date',
      },
      subscribe: {
        required: false,
        type: 'boolean',
      },
      'vehicle.vin': {
        required: false,
        type: 'string',
      },
      'loyalty.loyaltyStatus': {
        required: false,
        type: 'string',
      },
      'loyalty.rewardRedemption.redemptionPoint': {
        required: false,
        type: 'integer',
      },
      terms: {
        required: false,
        type: 'boolean',
      },
      'crm.abcClassification': {
        required: false,
        type: 'string',
      },
      'loyalty.rewardAmount': {
        required: false,
        type: 'float',
      },
      'vehicle.registrationDate': {
        required: false,
        type: 'date',
      },
    },
    dynamicSchema: false,
  },
  subscriptionsSchema: {
    fields: {
      'newsletter.commercial': {},
      'newsletter.passenger': {},
      promotion: {},
    },
  },
  internalSchema: {
    fields: {
      's4hana.s4Id': {
        required: false,
        type: 'string',
      },
      'crm.crmGuid': {
        required: false,
        type: 'string',
      },
      madId: {
        required: false,
        type: 'string',
      },
      'crm.crmId': {
        required: false,
        type: 'string',
      },
    },
    dynamicSchema: false,
  },
  addressesSchema: {
    fields: {
      soldTo: {
        entrance: {
          type: 'string',
          required: false,
          writeAccess: 'clientModify',
          allowNull: true,
          format: null,
          encrypt: 'AES',
        },
      },
      shipTo: {
        apartment: {
          type: 'string',
          required: false,
          writeAccess: 'clientModify',
          allowNull: true,
          format: null,
          encrypt: 'AES',
        },
      },
    },
  },
}

export const transformedSchema = [
  {
    id: 'profile',
    name: 'profile',
    value: false,
    branches: [
      { id: 'profile.photoURL', name: 'photoURL', value: false, branches: [], switchId: 'object' },
      {
        id: 'profile.oidcData',
        name: 'oidcData',
        value: false,
        branches: [
          {
            id: 'profile.oidcData.address',
            name: 'address',
            value: false,
            branches: [
              { id: 'profile.oidcData.address.locality', name: 'locality', value: false, branches: [], switchId: 'object' },
              { id: 'profile.oidcData.address.formatted', name: 'formatted', value: false, branches: [], switchId: 'object' },
            ],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.favorites',
        name: 'favorites',
        value: false,
        branches: [
          {
            id: 'profile.favorites.activities',
            name: 'activities',
            value: false,
            branches: [{ id: 'profile.favorites.activities.category', name: 'category', value: false, branches: [], switchId: 'object' }],
            switchId: 'object',
          },
          {
            id: 'profile.favorites.movies',
            name: 'movies',
            value: false,
            branches: [{ id: 'profile.favorites.movies.name', name: 'name', value: false, branches: [], switchId: 'object' }],
            switchId: 'object',
          },
        ],
        switchId: 'object',
      },
      {
        id: 'profile.certifications',
        name: 'certifications',
        value: false,
        branches: [{ id: 'profile.certifications.number', name: 'number', value: false, branches: [], switchId: 'object' }],
        switchId: 'object',
      },
      { id: 'profile.religion', name: 'religion', value: false, branches: [], switchId: 'object' },
    ],
    switchId: 'object',
  },
  {
    id: 'data',
    name: 'data',
    value: false,
    branches: [
      {
        id: 'data.loyalty',
        name: 'loyalty',
        value: false,
        branches: [
          { id: 'data.loyalty.rewardPoints', name: 'rewardPoints', value: false, branches: [], switchId: 'object' },
          {
            id: 'data.loyalty.rewardRedemption',
            name: 'rewardRedemption',
            value: false,
            branches: [
              { id: 'data.loyalty.rewardRedemption.redemptionDate', name: 'redemptionDate', value: false, branches: [], switchId: 'object' },
              { id: 'data.loyalty.rewardRedemption.redemptionPoint', name: 'redemptionPoint', value: false, branches: [], switchId: 'object' },
            ],
            switchId: 'object',
          },
          { id: 'data.loyalty.loyaltyStatus', name: 'loyaltyStatus', value: false, branches: [], switchId: 'object' },
          { id: 'data.loyalty.rewardAmount', name: 'rewardAmount', value: false, branches: [], switchId: 'object' },
        ],
        switchId: 'object',
      },
      {
        id: 'data.vehicle',
        name: 'vehicle',
        value: false,
        branches: [
          { id: 'data.vehicle.model', name: 'model', value: false, branches: [], switchId: 'object' },
          { id: 'data.vehicle.vin', name: 'vin', value: false, branches: [], switchId: 'object' },
          { id: 'data.vehicle.registrationDate', name: 'registrationDate', value: false, branches: [], switchId: 'object' },
        ],
        switchId: 'object',
      },
      {
        id: 'data.crm',
        name: 'crm',
        value: false,
        branches: [
          { id: 'data.crm.isProspect', name: 'isProspect', value: false, branches: [], switchId: 'object' },
          { id: 'data.crm.abcClassification', name: 'abcClassification', value: false, branches: [], switchId: 'object' },
        ],
        switchId: 'object',
      },
      { id: 'data.subscribe', name: 'subscribe', value: false, branches: [], switchId: 'object' },
      { id: 'data.terms', name: 'terms', value: false, branches: [], switchId: 'object' },
    ],
    switchId: 'object',
  },
  {
    id: 'subscriptions',
    name: 'subscriptions',
    value: false,
    branches: [
      {
        id: 'subscriptions.newsletter.commercial',
        name: 'newsletter.commercial',
        value: false,
        branches: [
          { id: 'subscriptions.newsletter.commercial.isSubscribed', name: 'isSubscribed', value: false, branches: [] },
          { id: 'subscriptions.newsletter.commercial.tags', name: 'tags', value: false, branches: [] },
          { id: 'subscriptions.newsletter.commercial.lastUpdatedSubscriptionState', name: 'lastUpdatedSubscriptionState', value: false, branches: [] },
          {
            id: 'subscriptions.newsletter.commercial.doubleOptIn',
            name: 'doubleOptIn',
            value: false,
            branches: [{ id: 'subscriptions.newsletter.commercial.doubleOptIn.isExternallyVerified', name: 'isExternallyVerified', value: false, branches: [] }],
          },
        ],
        switchId: 'object',
      },
      {
        id: 'subscriptions.newsletter.passenger',
        name: 'newsletter.passenger',
        value: false,
        branches: [
          { id: 'subscriptions.newsletter.passenger.isSubscribed', name: 'isSubscribed', value: false, branches: [] },
          { id: 'subscriptions.newsletter.passenger.tags', name: 'tags', value: false, branches: [] },
          { id: 'subscriptions.newsletter.passenger.lastUpdatedSubscriptionState', name: 'lastUpdatedSubscriptionState', value: false, branches: [] },
          {
            id: 'subscriptions.newsletter.passenger.doubleOptIn',
            name: 'doubleOptIn',
            value: false,
            branches: [{ id: 'subscriptions.newsletter.passenger.doubleOptIn.isExternallyVerified', name: 'isExternallyVerified', value: false, branches: [] }],
          },
        ],
        switchId: 'object',
      },
      {
        id: 'subscriptions.promotion',
        name: 'promotion',
        value: false,
        branches: [
          { id: 'subscriptions.promotion.isSubscribed', name: 'isSubscribed', value: false, branches: [] },
          { id: 'subscriptions.promotion.tags', name: 'tags', value: false, branches: [] },
          { id: 'subscriptions.promotion.lastUpdatedSubscriptionState', name: 'lastUpdatedSubscriptionState', value: false, branches: [] },
          {
            id: 'subscriptions.promotion.doubleOptIn',
            name: 'doubleOptIn',
            value: false,
            branches: [{ id: 'subscriptions.promotion.doubleOptIn.isExternallyVerified', name: 'isExternallyVerified', value: false, branches: [] }],
          },
        ],
        switchId: 'object',
      },
    ],
    switchId: 'object',
  },
  {
    id: 'internal',
    name: 'internal',
    value: false,
    branches: [
      {
        id: 'internal.s4hana',
        name: 's4hana',
        value: false,
        branches: [{ id: 'internal.s4hana.s4Id', name: 's4Id', value: false, branches: [], switchId: 'object' }],
        switchId: 'object',
      },
      {
        id: 'internal.crm',
        name: 'crm',
        value: false,
        branches: [
          { id: 'internal.crm.crmGuid', name: 'crmGuid', value: false, branches: [], switchId: 'object' },
          { id: 'internal.crm.crmId', name: 'crmId', value: false, branches: [], switchId: 'object' },
        ],
        switchId: 'object',
      },
      { id: 'internal.madId', name: 'madId', value: false, branches: [], switchId: 'object' },
    ],
    switchId: 'object',
  },
  {
    id: 'addresses',
    name: 'addresses',
    value: false,
    branches: [
      {
        id: 'addresses.soldTo',
        name: 'soldTo',
        value: false,
        branches: [{ id: 'addresses.soldTo.entrance', name: 'entrance', switchId: 'object', value: false, branches: [] }],
        switchId: 'object',
      },
      {
        id: 'addresses.shipTo',
        name: 'shipTo',
        value: false,
        branches: [{ branches: [], id: 'addresses.shipTo.apartment', name: 'apartment', switchId: 'object', value: false }],
        switchId: 'object',
      },
    ],
    switchId: 'object',
  },
]
