name: Checkmarx One

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  checkmarx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkmarx One SAST scan
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://checkmarx.tools.sap
          cx_tenant: sap
          cx_client_id: ${{ secrets.CHECKMARX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          project_name: sap-customer-data-cloud-toolkit
          scan_params: --scan-types sast --sast-preset-name "SAP Corp"
